language: node_js

node_js:
  - 14

dist: bionic

addons:
  apt:
    packages:
      - vlc

services:
  - xvfb

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3

before_script:
  - vlc -I qt --extraintf http --http-port 8080 --http-host localhost --http-password 1234 "https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_1280_10MG.mp4" 2> vlc.log > /dev/null &
  - sleep 3

after_failure:
  - cat vlc.log